version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: box
      POSTGRES_DB: box_db
      POSTGRES_PASSWORD: local
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - 'sh'
      - '-c'
      - 'npm install && npm run dev'
    volumes:
      - .:/home/app/
    links:
      - db
    depends_on:
      - db
    ports:
      - "3030:3030"
volumes:
  data:
    driver: local