import Head from 'next/head'

export default function Home() {
  return (
    <div className="bg-slate-800 text-slate-200 h-screen font-mono">
      <Head>
        <title>Box | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center content-center">
        <form className="flex-row min-w-[600px] shadow-lg bg-slate-500 mt-10">
          <div className="w-full text-3xl subpixel-antialiased text-center p-2 mb-10">
            BOX
          </div>
          <div className="w-full flex justify-center">
            <div className="min-w-[350px] max-w-[500px]">
              <label htmlFor="username" className="block text-sm">
                Username
              </label>
              <input
                type="text"
                name="username"
                className="w-full border bg-slate-700 border-slate-900 rounded outline-none"
              />
            </div>
          </div>
          <div className="w-full flex justify-center mt-6">
            <div className="min-w-[350px] max-w-[500px]">
              <label htmlFor="password" className="block text-sm">
                Password
              </label>
              <input
                type="password"
                name="password"
                className="w-full border bg-slate-700 border-slate-900 rounded outline-none"
              />
            </div>
          </div>
          <div className="w-full flex justify-center mt-10 mb-6">
            <button type="submit" className="rounded-full bg-emerald-600 shadow-md min-w-[350px] max-w-[500px]">
              LOGIN
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
